language: go
before_script:
- go build
- sed -i -e "s/@DEV@/$TRAVIS_TAG($TRAVIS_COMMIT)/" main.go
before_install:
- go get github.com/mitchellh/gox
before_deploy:
- gox --os linux --arch "386 arm arm64 amd64"
go:
- 1.x
- 1.10.x
- master
matrix:
  allow_failures:
  - go: master
deploy:
  provider: releases
  api_key:
    secure: hyyNuEf4I91Fy/tt6sBVFLFwbYGrLdS1/MX91UU3eVVurCIiCC4xtAKXBYieImnjdwuMal5ApmC6QTafTmidNQ07cMjLyNqXj2iMAmLQ81RYLNVdSeSVf+tGTDjWx8Ag8vwnX/aSNZ35O38Ur99tPDmmvyQeU4Gtoth2o7uRs2l7+gYlCXnIokWeJHm9N9ENsRWt7WtYCMGRS7RS0bmcBLI9o54qjWIE++euRm61MndcMOMxXzWeAYqfF4dbhGbLH9IfrEVk9LW1YCxxpKzMN7aTn2Xy1JqxvU6PWJfAv9CF7G8DKCJl+ygJZyfY9MfGmn0SGdP26EM98Uh82Gcw/NLdzD9wH0cWvMvwtxQ0VgQIU1bkbBKsEmidFLJbCzCvHQj2gAJ+fDOODzXr8KSe2cALYg8GtdAa/JGNznu8c4CbPcBnykrhqBPK4AP1tLpt+DKrD3vYRcG4l9r191rq4qOWeSC5iCUOllcI4O0oR/sF5DIWfiZ9l9GjOA+7ffX8Hkk40F8HJH/QJa7fMZBqQpvyBwG5C243qI36hPSkE+69ggAoVfgxuyySvFL4TbZOdkWtY19Xs9hsd4MP67CnNz9773uNoMsT6PX5jxpVFum5hQADkdlGRgXVyVQtSoDLYmPt+HDaopqanHxRqpLo/pyW1G/xGFc42VkiKpB3zNg=
  file:
    - shellflow_linux_386
    - shellflow_linux_amd64
    - shellflow_linux_arm
    - shellflow_linux_arm64
  on:
    repo: informationsea/shellflow
    tags: true
  skip_cleanup: true
