[[Command]]
RegExp = "mkdir +(-p +)?[^;&]+"
RunImmediate = true

[[Command]]
RegExp = "example_dont_inheirt_path"
DontInheirtPath = true

[[Command]]
RegExp = "gatk .*"
SGEOption = ["-l", "s_vmem=20G,mem_req=20G", "-pe", "def_slot", "2"]

[[Command]]
RegExp = "samtools .*"
SGEOption = ["-l", "s_vmem=10G,mem_req=10G", "-pe", "def_slot", "2"]

[[Command]]
RegExp = "java .*"
SGEOption = ["-l", "s_vmem=40G,mem_req=40G"]

