// Code generated by "stringer -type=WorkflowState"; DO NOT EDIT.

package main

import "strconv"

const _WorkflowState_name = "WorkflowDoneWorkflowRunningWorkflowFailedWorkflowUnknown"

var _WorkflowState_index = [...]uint8{0, 12, 27, 41, 56}

func (i WorkflowState) String() string {
	if i < 0 || i >= WorkflowState(len(_WorkflowState_index)-1) {
		return "WorkflowState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WorkflowState_name[_WorkflowState_index[i]:_WorkflowState_index[i+1]]
}
